email:
  username: "xxxx@xxxx.com"
  password: ""
  sender: "七牛云报警服务"
  receiver: "xxxx@xxxx.com"
  smtpPort: "465"
  smtpHost: "smtp.exmail.qq.com" #

qiniu:
  accessKey: ""
  secretKey: ""

ssl:
  duration: 300s # 5分钟一次
  sslPath : "./data/clientMagic"
  email : "xxxx@xxxx.com"
  aliyun:
    accessKeyID: ""
    accessKeySecret: ""
  db : "./data/sqlite/ssl.db"


